text_1= input("Напишите кол-во книг")
text_2= input("Напишите кол-во канцтоваров")
text_3= input("Напишите кол-во игрушек")
book=int(text_1*2)
kanc=int(text_2*1.5)
toys=int(text_3*3)
answer=(book+kanc+toys)
print("Общий объём:"+answer+"м^3")